/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.7.0                                               */
/*  Date (dd.mm.yyyy): 19. 6.2021   Time (hh:mm): 00:02                        */
/*******************************************************************************/


#ifndef _H747_TEST_MAIN_DISPLAY_RESOURCES_H_
#define _H747_TEST_MAIN_DISPLAY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define MAIN_DISPLAY 0
#define MAIN_DISPLAY_COLOR_FORMAT GX_COLOR_FORMAT_32ARGB
#define MAIN_DISPLAY_X_RESOLUTION 800
#define MAIN_DISPLAY_Y_RESOLUTION 480
#define MAIN_DISPLAY_DEFAULT_THEME 0
#define MAIN_DISPLAY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define MAIN_DISPLAY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define MAIN_DISPLAY_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define GX_FONT_ID_CASCADIACODE 4
#define MAIN_DISPLAY_FONT_TABLE_SIZE 5

/* Pixelmap ID definitions                                                     */

#define MAIN_DISPLAY_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_3 2
#define MAIN_DISPLAY_STRING_TABLE_SIZE 3

#endif                                       /* sentry                         */
